import C from '../config/colors.config';

const feedbackStyles = {
    toastOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
  },
    toastCard: {
    width: '100%',
    maxWidth: 520,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#11111B',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.38)',
    shadowColor: '#7B2FFF',
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 16,
  },
    toastSuccess: {
    borderColor: 'rgba(16, 185, 129, 0.5)',
    backgroundColor: '#0C1714',
  },
    toastWarning: {
    borderColor: 'rgba(245, 158, 11, 0.55)',
    backgroundColor: '#191409',
  },
    toastError: {
    borderColor: 'rgba(239, 68, 68, 0.55)',
    backgroundColor: '#1A0D10',
  },
    toastMarker: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#050508',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.5)',
    shadowColor: '#7B2FFF',
    shadowOpacity: 0.45,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
    overflow: 'hidden',
    flexShrink: 0,
  },
    toastLogoImage: {
    width: 30,
    height: 30,
    borderRadius: 8,
  },
    toastMarkerSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.14)',
    borderColor: '#10B981',
  },
    toastMarkerWarning: {
    backgroundColor: 'rgba(245, 158, 11, 0.14)',
    borderColor: '#F59E0B',
  },
    toastMarkerError: {
    backgroundColor: 'rgba(239, 68, 68, 0.14)',
    borderColor: '#EF4444',
  },
    toastMarkerText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
    toastTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.15,
  },
    toastMessage: {
    color: '#9D9DB0',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 2,
    fontWeight: '500',
  },
    confirmOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
    confirmCard: {
    width: '100%',
    maxWidth: 430,
    borderRadius: 14,
    backgroundColor: '#101018',
    borderWidth: 1,
    borderColor: '#272738',
    padding: 18,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.45,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 16 },
    elevation: 20,
  },
    confirmAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
    confirmAccentDanger: {
    backgroundColor: '#EF4444',
  },
    confirmAccentInfo: {
    backgroundColor: C.purple,
  },
    confirmTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 4,
    marginBottom: 8,
  },
    confirmMessage: {
    color: '#A8A8B8',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 18,
  },
    confirmActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
    confirmCancelBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: '#29293A',
  },
    confirmCancelText: {
    color: '#D8D8E6',
    fontSize: 11,
    fontWeight: '800',
  },
    confirmPrimaryBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
    confirmDangerBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
    borderColor: '#EF4444',
  },
    confirmInfoBtn: {
    backgroundColor: C.purple,
    borderColor: C.purple,
  },
    confirmPrimaryText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
  },
};

export default feedbackStyles;
