import C from '../config/colors.config';

const profileStyles = {
    profilePanel: {
    backgroundColor: '#0C0C12',
    borderWidth: 1,
    borderColor: '#20202F',
    borderRadius: 12,
    padding: 14,
    marginTop: -4,
    marginBottom: 16,
  },
    profileHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(123, 47, 255, 0.07)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.24)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
    profileSavePill: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.38)',
  },
    profileSavePillDirty: {
    backgroundColor: 'rgba(123, 47, 255, 0.14)',
    borderColor: 'rgba(123, 47, 255, 0.5)',
  },
    profileSaveDot: {
    color: '#10B981',
    fontSize: 9,
    fontWeight: '900',
    lineHeight: 11,
  },
    profileSaveDotDirty: {
    color: C.purpleSoft,
  },
    profileSaveText: {
    color: '#DDFCF0',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.55,
  },
    profileSaveTextDirty: {
    color: '#FFFFFF',
  },
    profileHeroCopy: {
    flex: 1,
    paddingRight: 76,
  },
    profileAvatar: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.purple,
  },
    profileAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
    profileHeroTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
    profileHeroSub: {
    color: '#A8A8B8',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
  },
    profileMultilineInput: {
    minHeight: 74,
    lineHeight: 17,
  },
    profileSectionLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#E2E2E9',
    marginBottom: 8,
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.45,
  },
    profileChipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginBottom: 13,
  },
    profileChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#141420',
    borderWidth: 1,
    borderColor: '#242436',
  },
    profileChipActive: {
    backgroundColor: 'rgba(123, 47, 255, 0.14)',
    borderColor: 'rgba(123, 47, 255, 0.58)',
  },
    profileChipText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#8A8A9D',
  },
    profileChipTextActive: {
    color: C.purpleSoft,
  },
    profileToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#11111A',
    borderWidth: 1,
    borderColor: '#242436',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
    profileToggleTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
    profileToggleSub: {
    color: '#8A8A9D',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
  },
    profileSwitch: {
    minWidth: 48,
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: '#333344',
  },
    profileSwitchActive: {
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderColor: 'rgba(123, 47, 255, 0.45)',
  },
    profileSwitchText: {
    color: '#8A8A9D',
    fontSize: 9,
    fontWeight: '900',
  },
    profileSwitchTextActive: {
    color: C.purpleSoft,
  },
    profilePreviewBox: {
    backgroundColor: '#050508',
    borderWidth: 1,
    borderColor: '#1E1E2C',
    borderRadius: 10,
    padding: 12,
    marginTop: 2,
    marginBottom: 12,
  },
    profilePreviewLabel: {
    color: C.purpleSoft,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
    profilePreviewText: {
    color: '#A8A8B8',
    fontSize: 10,
    lineHeight: 15,
  },
    profileResetBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#333344',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    paddingVertical: 10,
  },
    profileResetBtnText: {
    color: '#A8A8B8',
    fontSize: 10,
    fontWeight: '900',
  },
  resetPanel: {
    backgroundColor: '#0C0C12',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.22)',
    borderRadius: 12,
    padding: 14,
    marginTop: -4,
    marginBottom: 16,
  },
    resetActionBtn: {
    backgroundColor: '#11111A',
    borderWidth: 1,
    borderColor: '#242436',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
    resetActionTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
    resetActionSub: {
    color: '#8A8A9D',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 4,
  },
    resetDangerBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.32)',
    borderRadius: 10,
    padding: 12,
  },
    resetDangerTitle: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '900',
  },
    resetDangerSub: {
    color: '#FCA5A5',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 4,
  },
};

export default profileStyles;
