import C from '../config/colors.config';

const sidebarStyles = {
  sidebarScrim: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    zIndex: 999,
  },
  sidebarDrawer: {
    width: 280,
    flex: 1,
    backgroundColor: '#08080E',
    borderRightWidth: 1,
    borderRightColor: 'rgba(123, 47, 255, 0.45)',
    paddingHorizontal: 14,
    paddingBottom: 0,
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#161622',
  },
  sidebarTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  sidebarCloseBtn: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1E1E2C',
  },
  newChatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(123, 47, 255, 0.12)',
    borderRadius: 10,
    paddingVertical: 10,
    marginTop: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.3)',
  },
  newChatBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: C.purpleSoft,
    letterSpacing: 0.4,
  },
  searchContainer: {
    backgroundColor: '#0D0D14',
    borderWidth: 1,
    borderColor: '#1E1E2C',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: {
    color: '#FFFFFF',
    fontSize: 11.5,
    padding: 0,
    flex: 1,
  },
  timeframeHeader: {
    fontSize: 9,
    fontWeight: '800',
    color: '#3A3A50',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 6,
    marginTop: 14,
    paddingHorizontal: 4,
  },
  sidebarScroll: {
    flex: 1,
  },
  noHistoryText: {
    fontSize: 11,
    color: '#4E4E61',
    textAlign: 'center',
    marginTop: 30,
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 6,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.18)',
  },
  historyItemActive: {
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    borderColor: 'rgba(123, 47, 255, 0.2)',
  },
  historyItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  historyDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  historyItemText: {
    fontSize: 11.5,
    fontWeight: '500',
    color: '#6A6A7D',
    flex: 1,
  },
  historyItemTextActive: {
    color: '#E2E2F0',
    fontWeight: '600',
  },
  historyDeleteBtn: {
    padding: 4,
    opacity: 0.5,
  },
  sidebarFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#111120',
    paddingTop: 12,
    marginTop: 'auto',
    backgroundColor: '#08080E',
  },
  sidebarFooterLogo: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.45)',
    backgroundColor: '#050508',
    shadowColor: '#7B2FFF',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
  },
  sidebarFooterTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#C0C0D8',
    letterSpacing: 0.3,
  },
  sidebarFooterSub: {
    fontSize: 9,
    color: '#3E3E52',
    marginTop: 1,
    letterSpacing: 0.2,
  },
  activeIndicator: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: C.green,
    shadowColor: C.green,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 5,
  },
};

export default sidebarStyles;
